runtime: python310 

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  
  MONGO_URI: mongodb+srv://preetr841:GyfWFDtJVoFldicc@cluster0.e9inxl5.mongodb.net/?appName=Cluster0  


entrypoint: uvicorn main:app --host=0.0.0.0 --port=8000
